### ISSUE TITLE
oci-public-ip fails

### ISSUE THREAD

**Issue by JamesMastersOracle** [oracle/oci-utils#76]
Hi, running `oci-public-ip` is failing in my oci instance:

```
  Instance shape: VM.Standard2.1
  Image ID: ocid1.image.oc1.iad.aaaaaaaabip6l5i5ikqsnm64xwrw2rrkj3tzo2dv47frowlt3droliwpvfaa
  ociAdName: iad-ad-1
  regionIdentifier: us-ashburn-1
```

Stacktrace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/oci_utils/impl/oci-public-ip-main.py", line 175, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/oci_utils/impl/oci-public-ip-main.py", line 140, in main
    stun_host=args.stun_server)[1]
  File "/usr/lib/python3.6/site-packages/oci_utils/packages/stun/__init__.py", line 332, in get_ip_info
    stun_host=stun_host, stun_port=stun_port)
  File "/usr/lib/python3.6/site-packages/oci_utils/packages/stun/__init__.py", line 256, in get_nat_type
    ret = stun_test(s, stun_host, port, source_ip, source_port)
  File "/usr/lib/python3.6/site-packages/oci_utils/packages/stun/__init__.py", line 178, in stun_test
    bind_resp_msg = dictValToMsgType[msgtype] == "BindResponseMsg"
KeyError: b'0101'
```

I've made no changes to the instance since provisioning, other than installing a jvm package (java-latest-openjdk-headless.x86_64) and mounting a block volume.

James

**Comment by ejannett** [comment]
Hi,

Can you confirm the oci-utils version used on this instance ?

thank you
regards
manu

**Comment by JamesMastersOracle** [comment]
Hi Manu,

```
[opc@jmeter-primary oci_utils]$ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
docutils (0.14)
lockfile (0.11.0)
oci-utils (0.11.0)
pip (9.0.3)
python-daemon (2.1.2)
sdnotify (0.3.2)
setuptools (39.2.0)
```

The tool doesn't seem to have a version command, so here is the output of pip3 list.  I didn't install this package so I assume this is the way it's been installed.

Thanks,
James

**Comment by ejannett** [comment]
Hi,
Exact the version is taken form the rpm.
I am interested to know how oci-utils was installed,  as we only deliver it as rpm package on Oracle Yum repositories.

regards
manu

**Comment by ejannett** [comment]
Root cause of this issue caused by recent move to python3 code

**Comment by ejannett** [comment]
fix by next release

**Comment by ejannett** [comment]
fixed
